### ISSUE TITLE
Repo access

### ISSUE THREAD

**Issue by paulstraw** [raynjamin/Imgix-CSharp#3]
Hey @raynjamin! I'm Paul, Developer Relations at imgix. I'm going to be making some updates to this library to support some of our new features, and was wondering if you'd rather I submit pull requests, or if you'd be okay with giving me direct repo access. We'd also be happy to pull this over to the imgix GitHub organization and handle it all going forward, if you'd prefer. Any of those options work for me, just let me know how you want to move forward! 😁

**Comment by raynjamin** [comment]
@paulstraw Hey man, I knew this day would come at some point. I would say let's move it over to the Imgix organization, but there is also a nuget feed that needs to be maintained when updates happen.

For now maybe make pull requests and when I accept them I'll pull them down and update the nupkg?

**Comment by paulstraw** [comment]
Okay, sounds good to me for now. Do you have a sense of how the NuGet transfer might work if/when you want to flip the switch?

**Comment by raynjamin** [comment]
Yeah I think I can just add whatever imgix-owned account as an owner.

**Comment by paulstraw** [comment]
Sounds good. Whenever you decide you want to make that happen, let me know and we'll get it all sorted! :)
